name: Ensure the build is passing

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm ci
      - name: Run the build to ensure it doesn't fail
        run: npm run build
